wget http://nces.ed.gov/ipeds/datacenter/data/C2012_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2011_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2010_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2009_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2008_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2007_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2006_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2005_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2004_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2003_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2002_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2001_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C2000_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9899_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9798_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9697_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9596_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9495_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9394_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9293_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9192_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C9091_A.zip
wget http://nces.ed.gov/ipeds/datacenter/data/C8990_A.zip
